config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :comments

  devise_for :users
  resources :line_items

  resources :carts

  get 'store/index'

  resources :products
  resources :users
  get 'user/index'

  resources :photos, only: [:new, :create, :index]

  root 'posts#index'
  
 
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
 
  resources :conversations do
    resources :messages
  end

  resources :posts do
    resources :comments, :only => [:create]
  end

  resources :products do
    resources :comments, :only => [:create]
  end
  get 'post/index'
  resources :users do
    resources :comments, :only => [:create]
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	def add_product(product_id,product_price)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id,:price => product_price)
		end
		current_item
	end
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, :polymorphic => true
	belongs_to :user
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, :foreign_key => :sender_id, class_name: "User"
	belongs_to :recipient, :foreign_key => :recipient_id, class_name: "User"

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, :scope => :recipient_id
	 scope :involving, -> (user) do
    	where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  	end
 
  	scope :between, -> (sender_id, recipient_id) do
    	where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  	end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	def total_price
		price * quantity
	end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	dragonfly_accessor :image
  
  	belongs_to :product
  	belongs_to :post
  	# validates :image, presence: true
  	validates_size_of :image, maximum: 500.kilobytes,
                    message: "should be no more than 500 KB", if: :image_changed?

  	validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
                     message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :body, :title
	belongs_to :user
	has_many :comments, :as => :commentable
	has_many :photos
	accepts_nested_attributes_for :photos
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :title, :description, presence: true
	validates :title, uniqueness: true
	# validates :image_url, uniqueness: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :price, :numericality => {:less_than_or_equal_to => 1000}
	def long_title
		"#{title} - #{description}"
	end
	# attr_accessible :image
	has_many :line_items
	belongs_to :user
	has_many :comments, :as => :commentable
	has_many :photos
	accepts_nested_attributes_for :photos
	before_destroy :ensure_not_referenced_by_any_line_item
	private
		def ensure_not_referenced_by_any_line_item	
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
			end
		end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :conversations, :foreign_key => :sender_id, dependent: :destroy
  has_many :products, -> {order('title ASC')},
						:dependent => :nullify, :foreign_key => :user_id
  has_many :comments, dependent: :destroy
  has_many :responses, :through => :products, :source => :comments , dependent: :destroy
  after_create :create_default_conversation
  # after_create :send_admin_mail

  def send_admin_mail
    UserMailer.welcome_email(self).deliver
  end
  
  private

  # for demo purposes

  def create_default_conversation
    Conversation.create(sender_id: 1, recipient_id: self.id) unless self.id == 1
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
   def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    #@cart = current_cart
    @cart.destroy
    #session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, size = 30, title = user.name)
  		image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
	end
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
	def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end
 
  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/views/confirmable/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li>
              <%= link_to "Hi, #{current_user.name}", root_path %>
            </li>
            <li>
              <%= link_to "Inbox", users_path %>
            </li>
            <li>
              <%= link_to "Products", products_path %>
            </li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete	  %>
            </li>
        <% else %>
            <li>
              <%= link_to "Signin", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Signup", new_user_registration_path %>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
 
  <title>-h0angnhat-</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
  <!-- shiv here -->
</head>
 
<body>
 
<%= render 'layouts/nav' %>
 
<div class="container">
  <!-- flash messages here -->
  <%= yield %>
</div>
<audio id="chatAudio"><source src="/uploads/2.mp3" type="audio/mpeg"></audio>