config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :comments

  devise_for :users
  resources :line_items

  resources :carts

  get 'store/index'

  resources :products
  resources :users
  get 'user/index'

  resources :photos, only: [:new, :create, :index]

  root 'posts#index'
  
 
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
 
  resources :conversations do
    resources :messages
  end

  resources :posts do
    resources :comments, :only => [:create]
  end

  resources :products do
    resources :comments, :only => [:create]
  end
  get 'post/index'
  resources :users do
    resources :comments, :only => [:create]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :title, :description, presence: true
	validates :title, uniqueness: true
	# validates :image_url, uniqueness: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :price, :numericality => {:less_than_or_equal_to => 1000}
	def long_title
		"#{title} - #{description}"
	end
	# attr_accessible :image
	has_many :line_items
	belongs_to :user
	has_many :comments, :as => :commentable
	has_many :photos
	accepts_nested_attributes_for :photos
	before_destroy :ensure_not_referenced_by_any_line_item
	private
		def ensure_not_referenced_by_any_line_item	
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
			end
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, :set_commentable, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access product #{ params[ :id ]}" 
      redirect_to products_url, :notice => 'Invalid product'
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.photos.clear
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
    def set_commentable
      @commentable = Product.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description,:price,photos_attributes: [:id, :image, :_destroy])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title,:placeholder => 'Enter text here...' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, row: 20%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <h2> Image </h2>
  <p> Multi File </p>
    <div class="form-group">
      <%= f.label :image, 'Choose files here' %>
      <%= f.file_field :image, required: true, multiple: true, name: 'product[photos_attributes][][image]' %>
    </div>
    
  <div class="row fileupload-buttonbar">
      <div class="span7"> 
        <button type="submit" class="btn btn-primary start" id="startbutton">
              <i class="glyphicon glyphicon-upload glyphicon-white"></i>
              <span>OK</span>
        </button>
      </div>
      
    </div>
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
<% end %>

<script>
  $(document).ready(function() {
    var multiple_photos_form = $('#new_photo');
    var wrapper = multiple_photos_form.find('.progress-wrapper');
    var bitrate = wrapper.find('.bitrate');
    var progress_bar = wrapper.find('.progress-bar');
    multiple_photos_form.fileupload({
      dataType: 'script',
      dropZone: $('#dropzone'),
      add: function (e, data) {
        types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
        file = data.files[0];
        if (types.test(file.type) || types.test(file.name)) {
          data.submit();
        }
        else { alert(file.name + " must be GIF, JPEG, BMP or PNG file"); }
      }
    });
    multiple_photos_form.on('fileuploadstart', function() {
      wrapper.show();
    });
    multiple_photos_form.on('fileuploaddone', function() {
      wrapper.hide();
      progress_bar.width(0);
    });
    multiple_photos_form.on('fileuploadsubmit', function (e, data) {
      data.formData = {'photo[author]': $('#photo_author').val()};
    });
    multiple_photos_form.on('fileuploadprogressall', function (e, data) {
      bitrate.text((data.bitrate / 1024).toFixed(2) + 'Kb/s');
      var progress = parseInt(data.loaded / data.total * 100, 10);
      progress_bar.css('width', progress + '%').text(progress + '%');
    });
    $(document).bind('dragover', function (e) {
      var dropZone = $('#dropzone'),
              timeout = window.dropZoneTimeout;
      if (!timeout) {
        dropZone.addClass('in');
      } else {
        clearTimeout(timeout);
      }
      var found = false,
              node = e.target;
      do {
        if (node === dropZone[0]) {
          found = true;
          break;
        }
        node = node.parentNode;
      } while (node != null);
      if (found) {
        dropZone.addClass('hover');
      } else {
        dropZone.removeClass('hover');
      }
      window.dropZoneTimeout = setTimeout(function () {
        window.dropZoneTimeout = null;
        dropZone.removeClass('in hover');
      }, 100);
    });
  });
</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<table>
<% @products.each do |product| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
<td>
<% if product.photos.any? %>
	<ul class="row" id="photos-list">
    	<li class="col-xs-3">
      	<%= link_to image_tag(product.photos.first.image.thumb('180x180#').url, class: 'img-thumbnail'),
        	product.photos.first.image.url, target: '_blank' %>
    	</li>
	</ul>
<% else %>
	<p> No Image </p>
<% end %>
</td>
<td class="list_description">
<dl>
<dt><%= link_to product.title, product %></dt>
</dl>
</td>
</tr>
<% end %>
</table>
<br/>
<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<h2> Image </h2>
<% if @product.photos.any? %>
	<% @product.photos.each do |photo| %>
	<ul class="row" id="photos-list">
    	<li class="col-xs-3">
      	<%= link_to image_tag(photo.image.thumb('180x180#').url, class: 'img-thumbnail'),
        	photo.image.url, target: '_blank' %>
    	</li>
	</ul>
<% end %>
<% else %>
	<p> No Image </p>
<% end %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<%= link_to "Delete", @product, method: :delete, data: { confirm: 'Are you sure?' } %>

<h2>Comments</h2>
<div id="comments">
   <%= render :partial => @product.comments %>
 </div>

<%= render '/comments/form'%>

<script>
  function refressPage(){
    location.reload(true) //load tu server, khong load tu cache
  }
  $(document).ready(function() {
    setTimeout("refressPage();", 10000);  
  })
</script>